modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="forest"
version="1.4.5"
displayName="Forest X Reborn"
displayURL="https://power-umc.ru/minecraft-java-edition/mods/5-forest-x-reborn.html"
logoFile="logo.png"
credits="Created by Environment Studios"
authors="Environment Studios"
description="The revival of the legendary Forest X Second Edition addon, but only for Minecraft Java Edition. "

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.forest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.forest]]
    modId="geckolib"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.forest]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

