# Automatically builds and publishes the mod when a new release is created on GitHub.
# It uploads the mod to GitHub, CurseForge and Modrinth.

name: Snapshot

on:
  push:
    branches:
      - "snapshot"
env:                                              
  MINECRAFT_VERSION: 1.20.1                      
  JAVA_VERSION: 17      
  VERSION: 1.4.0.231031
  RELEASE_NAME: Forest X Reborn 1.4.0.231031 Snapshot

jobs:
  build:
    runs-on: ubuntu-latest                        
    steps:                                        
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Publish mod to CurseForge and Modrinth
        id: publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 689955
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-id: 6SZBMNXj 
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          
          name: "${{env.RELEASE_NAME}}"                             
          version: "${{env.VERSION}}"
          version-type: beta
          changelog-file: SNAPSHOT_CHANGELOG.md                                      

          loaders: |
            forge
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"

          modrinth-featured: false
          fail-mode: warn	
          
      - name: Send Discord webhook
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "@everyone"
        env:
          DISCORD_WEBHOOK: "${{secrets.DISCORD_WEBHOOK}}"
          DISCORD_EMBEDS: |
            [{
              "title": "${{env.RELEASE_NAME}} for Minecraft ${{env.MINECRAFT_VERSION}} Released",
              "color": 14177041,
              "thumbnail": {
                "url": "https://sun9-38.userapi.com/impg/DT-sAuz6HXjQyDc-JUcNohnWvlFpPedLd7e5lw/vtp7gmTrGXQ.jpg?size=1920x1080&quality=95&sign=46ddcdaa7f11b953d45ce88907da7355&type=album"
              },
              "url": "https://www.curseforge.com/minecraft/mc-mods/forest-x-reborn",
              "fields": [
                  {
                    "name": "Download now:",
                    "value": "[<:curseforge:805066577871110196> CurseForge](https://www.curseforge.com/minecraft/mc-mods/forest-x-reborn)\n[<:modrinth:805066578215043092> Modrinth](https://modrinth.com/mod/forest-x-reborn)\n[<:github:805066578164580392> GitHub](https://github.com/Environment-Studios-Official/Forest-X-Reborn)",
                    "inline": true
                  }
              ],
              "footer": {
                "text": "Created by the Environment Studios team!",
                "icon_url": "https://sun9-8.userapi.com/impg/z07zX22x1cDSTI8mxViZSNmSq1ZgWQUH2V4S6Q/iS1pjti92qo.jpg?size=1280x1280&quality=95&sign=b28d93cf356dd02eb658598caec418ca&type=album"
              }
            }]
